<template>
  <NavBarUser></NavBarUser>
  <div class="container">
    <h2>Order menu</h2>
    <input v-model="from" class="input" type="from" placeholder="from" />
    <input v-model="to" class="input" type="to" placeholder="to" />
    <select v-model="taxitype" class="input">
      <option value="" disabled selected>taxi type</option>
      <option value="Econom">Econom</option>
      <option value="Comfort">Comfort</option>
      <option value="Business">Business</option>
    </select>
    <button class="auth-button" @click="submitForm()">Submit</button>
  </div>
  <div v-if="isLoading">
    <div class="loadingio-spinner-magnify-vs28tos9p0a">
      <div class="ldio-uwcdksru16">
        <div>
          <div>
            <div></div>
            <div></div>
          </div>
        </div>
      </div>
    </div>
    <p>Loading...</p>
  </div>
  <p v-text="message"></p>
  <div v-if="error">
    <error-component :error="error" />
  </div>
</template>
<script>
import axios from "axios";
import ErrorComponent from "./../ErrorComp.vue";
import NavBarUser from "./NavBarUser.vue";
export default {
  data() {
    return {
      taxitype: "",
      from: "",
      to: "",
      errorLog: false,
      isLoading: false,
    };
  },
  components: {
    ErrorComponent,
    NavBarUser,
  },
  methods: {
    submitForm() {
      this.isLoading = true;
      const token = localStorage.getItem("token_user");
      const user_id = localStorage.getItem("user_id");
      axios.defaults.headers.common["Authorization"] = `Bearer ${token}`;
      this.errorLog = false;
      const formData = {
        userID: Number(user_id),
        taxitype: this.taxitype,
        from: this.from,
        to: this.to,
      };
      console.log(formData);
      axios
        .post("http://localhost:8084/users/ordertaxi", formData)
        .then((response) => {
          this.errorLog = false;
          this.message = "success!";
          console.log(response);
          setTimeout(() => {
            this.$router.push("/user");
          }, 3000);
        })
        .catch((error) => {
          this.isLoading = false;
          this.error = error;
          console.log(error);
          if (String(error.response.status).includes("401")) {
            this.$router.push("/user-auth");
          }
        });
    },
  },
};
</script>
<style type="text/css">
.container {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.input {
  margin-bottom: 10px;
  padding: 8px;
}

.auth-button {
  background-color: #ff0000; /* Red color */
  color: white;
  padding: 10px 20px;
  border: none;
  cursor: pointer;
  font-size: 16px;
}

.auth-button:hover {
  background-color: #cc0000; /* Darker red color on hover */
}

.auth-button:active {
  background-color: #990000; /* Even darker red color when clicked */
}

@keyframes ldio-uwcdksru16 {
  0% {
    transform: translate(2px, 2px);
  }
  33.33% {
    transform: translate(102px, 2px);
  }
  66.66% {
    transform: translate(42px, 102px);
  }
  100% {
    transform: translate(2px, 2px);
  }
}

.ldio-uwcdksru16 > div {
  transform: scale(0.8);
  transform-origin: 100px 100px;
}

.ldio-uwcdksru16 > div > div {
  animation: ldio-uwcdksru16 1s linear infinite;
  position: absolute;
}

.ldio-uwcdksru16 > div > div div:nth-child(1) {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 12px solid #ff0000;
  background: #ffffff;
}

.ldio-uwcdksru16 > div > div div:nth-child(2) {
  width: 17px;
  height: 51px;
  transform: rotate(-45deg);
  background: #ff0000;
  border-radius: 0 0 8px 8px;
  position: absolute;
  top: 68px;
  left: 85px;
}
.loadingio-spinner-magnify-vs28tos9p0a {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-uwcdksru16 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-uwcdksru16 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
